# Course Materials

Before the course begins, information will be shared via email and the class [Google Drive](xxxx).
 
- Trip Guidebook – will be posted as a Google Drive link and a printed copy handed out at the beginning of class.
2

Technical references online (you can get hard copies from the NRCS Distribution Center, print, or download to your device so you have access in the field):

- Keys to Soil Taxonomy

- Hydric Soil Indicators Ver. 8.2

- Field Guide for Describing and Sampling Soils Ver. 3.0

- Recommended articles and videos – shared on class google drive before the trip begins.

## Readings

Assigned readings from a variety of papers and books focused on topics relevant to the location and topic of the day. Copies of the required readings are in the “Syllabus and Course Reader”. The course also carries a book box with many other general references, relevant papers and books, which students can check out. Each day 1-2 papers are required readings that we will discuss over breakfast and/or dinner. The required readings are in the “Syllabus and Course Reader”. 

## Course Library

The course also carries a course library box with many other general references, relevant papers and books. Students can check these out for personal reading and as background for their course projects. The contents of the library are listed in the course “Syllabus and readings”.

### **Items not in manila folders: Books, data reports, natural history guidebooks, guides
to the Dalton Highway and floras:**

Argus, G. W. 2004. A guide to the identification of Salix (willows) in Alaska, the Yukon Territory and adjacent regions. 85 pp.

Armstrong, R. H. 1995. Guide to the Birds of Alaska. Alaska Northwest Books, Anchorage, AK. 322 pp.

Barreda, J. E., J. A. Knudson, D. A. Walker, M. K. Raynolds, A. N. Kade, and C. A. Munger. 2006.

Biocomplexity of Patterned Ground Data Report. Alaska Geobotany Center, Fairbanks, AK. 224 pp.

Brodo, I. M., S. D. Sharnoff, S. Sharnoff, and S. Laurie-Bourque. 2001. Lichens of North America. Yale University Press, New Haven.

Brown J, Kreig RA. 1983. Guidebook to permafrost and related features along the Elliot and Dalton highways, Fox to Prudhoe Bay, Alaska. Fairbanks, AK: Division of Geological and Geophysical Surveys.

Cody, W. J. 2000. Flora of the Yukon Territory. NRC Research Press, Ottawa.

Collette, D. W. 2004. Willows of Interior Alaska. U.S. Fish & Wildlife Service. 111 pp.

Douglas, David C., Patricia E. Reynolds, and E. B. Rhode. 2002. Arctic Refuge coastal plain terrestrial wildlife research summaries. No. 2002-0001. US Fish and Wildlife Service, Reston VA.

Harris, J. G. and M. W. Harris. 1999. Plant Identification Terminology, an Illustrated Glossary. Spring Lake Publishing, Spring Lake UT. 197 pp.

Hasselbach, L. and P. Neitlich. 1988. A genus key to the lichens of Alaska. U.S. National Park Service, Gates of the Arctic NP&P, Fairbanks AK. 36 pp.

Hobbie, J. E. and G. W. Kling, editors. 2014. Alaska's Changing Arctic: Ecological consequences for tundra, streams, and lakes. Oxford University Press, New York, NY.

Hulten, E. 1968. Flora of Alaska and Neighboring Territories. Stanford University Press, Stanford, CA.

Huryn, A and Hobbie, J. 2013. Land of Extremes: a natural history of the Arctic North Slope of Alaska. University of Chicago Press.

Jorgenson, M.T. (ed.). 2011. Coastal Region of Northern Alaska. Guidebook to Permafrost and Related Features. Guidebook 10. State of Alaska, Department of Natural Resources, Division of Geological and Geophysical Surveys.

Marshall, R. 1991 (reprint). Arctic Village: A 1930s Portrait of Wiseman, Alaska, University of Alaska Press, Fairbanks,

Mull, C. G. and Adams, K. E.1985. Dalton Highway, Yukon River to Prudhoe Bay, Alaska: Bedrock geology of the eastern Koyukuk basin, central Brooks Range, and east central Arctic Slope. 155 pp. 

Munsell-Color. 1994. Munsell Soil Color Charts. Macbeth Div. of Kollmorgan Instr. Corp, NY.

National Geographic Society. 1987. Filed Guide to the Birds of North America. 

Sibley, D. A. 2000. The Sibley Guide to Birds. National Audubon Society. Alfred A. Knopf, New York. 154 pp.

Skinner, Q. D., S. J. Wright, R. J. Henszey, J. L. Henszey, and S. K. Wyman. 2012. A Field Guide to Alaska Grasses. Alaska Dept. of Natural Resources, Palmer, AK. 384 pp.

Streever, W. 2006. Long-term ecological monitoring in BP’s North Slope oil fields. BP Exploration, Anchorage AK.

Streever, W. and S. Bishop. 2012. Long-term ecological monitoring in BP’s North Slope oil fields. BP Exploration, Anchorage AK.

Viereck, L. A. and E. L. Little, Jr. 1994. Alaska Trees and Shrubs. University of Alaska Press, Fairbanks, Alaska.

Vitt, D. H., J. E. Marsh, and R. B. Bovey. 2007. Mosses, Lichens and Ferns of Northwest North America. Lone Pine Publisher. 296 pp.

Walker, D. A. 1985. Vegetation and environmental gradients of the Prudhoe Bay region, Alaska. US Army Cold Regions Research and Engineering Laboratory, CRREL85-14, Hanover, NH. 240 pp.

Walker DA, Auerbach NA, Nettleton TK, Gallant A, Murphy SM. 1997. Happy Valley Permanent Vegetation Plots. Boulder, CO: University of Colorado. Data Report.

Walker, D. A., H. E. Epstein, V. E. Romanovsky, C.-L. Ping, G. J. Michaelsen, R. P. Daanen, Y. Shur, R. A. Peterson, W. B. Krantz, M. K. Raynolds, W. A. Gould, G. Gonzalez, D. J. Nicolsky, C. M. Vonlanthen, A. N. Kade, H. P. Kuss, A. M. Kelley, C. A. Munger, C. T. Tarnocai, N. V. Matveeva, and F. J. A. Daniels. 2008. Arctic patterned-ground ecosystems: A synthesis of studies along a North American Arctic Transect. Journal of Geophysical Research - Biogeosciences 113:G03S01, doi:10.1029/2007JG000504.

Walker DA, Hamilton TD, Ping C-L, Daanen RP, Streever WW. 2009. Dalton Highway Field Trip Guide for the Ninth International Conference on Permafrost. Fairbanks, AK: Division of Geological and Geophysical Surveys.

Walker, D. A., M. K. Raynolds, M. Buchhorn, and J. L. Peirce. 2014. Landscape and permafrost change in the Prudhoe Bay Oilfield, Alaska. Alaska Geobotany Center, University of Alaska, Fairbanks, Alaska.

Walker MD. 1990. Vegetation and floristics of pingos, Central Arctic Coastal Plain, Alaska. Stuttgart, Germany: J. Cramer

### **Items in manila folders (arranged alphabetically by author within subject folders):
Journal articles and book chapters:**

*ANIMALS*

Amstrup, S. C., G. York, T. L. McDonald, R. Nielson, and K. Simac. 2004. Detecting denning polar bears with forward-looking infrared (FLIR) imagery. Bioscience 54: 337–344.

Barnes, B. 1989. Freeze avoidance in a mammal: body temperatures below 0 degree C in an Arctic hibernator. Science 244:1593–1595.

Buck, C. L., and B. M. Barnes. 1999. Annual cycle of body composition and hibernation in free-living Arctic ground squirrels. Journal of Mammalogy 80: 430–442.

Felchhelm, R. G., B. Streever, and B. J. Gallaway. 2007. The Arctic Cisco (Coregonus autumnalis) subsistence and commercial fisheries, Colville River, Alaska: A conceptual model. Arctic 60: 421–429.

Klein, D. R., Meldgaard, M., & Fancy, S. G. (1987). Factors determining leg length in Rangifer tarandus. Journal of Mammalogy, 68(3), 642-655.

Klein, D. R., & Bay, C. 1994. Resource partitioning by mammalian herbivores in the high Arctic. Oecologia, 97(4): 439-450.

Klein, D. R. 1995. Arctic ungulates at the northern edge of terrestrial life. Rangifer, 16(2): 51-56.

Klein, D. R. 1999. Comparative social learning among arctic herbivores: the caribou, muskox and arctic hare. Pp 126-140 In Mammalian social learning: comparative and ecological perspectives (HO Box and KL Gibson, eds.). Cambridge University Press, United Kingdom.

Klein, D. R. 2001. Similarity in habitat adaptations of Arctic and African ungulates: evolutionary convergence or ecological divergence? Alces, 37(2): 245-252.

Klein, D. R. and et al. 2005. Management and conservation of wildlife in a changing arctic environment. Pages 597-648 in S. J. Hassol, editor. Impacts of a Warming Arctic, Arctic Climate Impact Assessment Scientific Report. Cambridge University Press, UK.

Liebezeit, J. R., S. J. Kendall, S. Brown, C. B. Johnson, P. Martin, T. L. McDonald, D. C. Payer, C. L. Rea, B. Streever, A. M. Wildman, and S. Zack. 2009. Influence of human development and predators on nest survival of tundra birds, Arctic Coastal Plain, Alaska. Ecological Applications 19:1628–1644.

Long, R. A., T. J. Martin, and B. M. Barnes (Eds.). 2005. Body temperature and activity patterns in free-living Arctic ground squirrels. Journal of Mammalogy 86:314–322. McDonald, T. L., W. J. Richardson, G. C. R, S. B. Blackwell, C. S. Nations, R. M. Nielson, and B. Streever. 2012. Detecting changes in the distribution of calling bowhead whales exposed to fluctuating anthropogenic sounds. Journal of Cetacean Research Management 12:91–106.

Noel, L. E., M. K. Butcher, M. A. Cronin, and B. Streever. 2006. Assessment of effects of an oil pipeline on caribou, Rangifer tarandus. The Canadian Field-Naturalist 120:325–330.

Owen, M., and J. Simerson. 2006. Can you hear me now? Polar bears and sensitivity to noise pollution. Conservation and Research for Endangered Species:1–2.

Sheriff, M. J., G. J. Kenagy, M. Richter, T. Lee, O. Toien, F. Kohl, C. L. Buck, and B. M. Barnes. 2011. Phenological variation in annual timing of hibernation and breeding in nearby populations of Arctic ground squirrels. Proceedings of the Royal Society B: Biological Sciences 278:2369–2375.

Sheriff, M. J., M. M. Richter, C. L. Buck, and B. M. Barnes. 2013. Changing seasonality and phenological responses of free-living male arctic ground squirrels: the importance of sex. Philosophical Transactions of the Royal Society B: Biological Sciences 368:20120480–20120480.

Stickney, A. A., T. Obritschkewitsch, R. M. Burgess. 2014. Shifts in fox den occupancy in the greater Prudhoe Bay Area, Alaska. Arctic 67: 196-202.

Williams, C. T., B. M. Barnes, and C. L. Buck. 2011. Daily body temperature rhythms persist under the midnight sun but are absent during hibernation in free-living arctic ground squirrels. Biology Letters 8:31–34.

Williams, C. T., M. J. Sheriff, J. A. Schmutz, F. Kohl, Ø. Tøien, C. L. Buck, and B. M. Barnes. 2011. Data logging of body temperatures provides precise information on phenology of reproductive events in a free- living Arctic hibernator. Journal of Comparative Physiology, B 181:1101–1109.

*CLIMATE CHANGE*

ACIA. 2004. Synthesis - Impacts of a Warming Arctic, Arctic Climate Impact Assessment Cambridge University Press, Cambridge, UK.

Hinzman, L. D., C. J. Deal, A. D. McGuire, S. H. Mernild, I. V. Polyakov, and J. E. Walsh. 2014. Trajectory of the Arctic as an integrated system. Ecological Applications. 

Raynolds, M. K., D. A. Walker, D. Verbyla, and C. A. Munger. 2013. Patterns of Change within a Tundra Landscape: 22-year Landsat NDVI Trends in an Area of the Northern Foothills of the Brooks Range, Alaska. Arctic, Antarctic, and Alpine Research 45:249–260.

*GEOLOGY*

Ellis J. M., Calkin P. E. 1979. Nature and distribution of glaciers, neoglacial moraines, and rock glaciers, east- central Brooks Range, Alaska. Arctic and Alpine Research 11: 403-420.

Hamilton TD. 1986. Late Cenozoic glaciation of the Central Brooks Range. Pages 9-49 in Hamilton TD, Reed KM, Thorson RM, eds. Glaciation in Alaska: the Geologic Record. Anchorage: Alaska Geological Society.

*HUMAN, INDUSTRIAL & SOCIAL SYSTEMS*

Chapin, F. S., III, M. Hoel, S. R. Carpenter, J. Lubchenco, B. Walker, T. V. Callaghan, C. Folke, S. A. Levin, K.-G. Mäler, C. Nilsson, S. Barrett, F. Berkes, A.-S. Crépin, K. Danell, T. Rosswall, D. Starrett, A. Xepapadeas, and S. A. Zimov. 2006. Building resilience and adaptation to manage Arctic change. Ambio Special Report 35:198–202.

Klein, D. R. 1973. The ethics of hunting and the antihunting movement. Transactions of the Thirty-Eighth North American Wildlife and Natural Resources Conference. 18-21 March 1973. Wildlife Management Institute, Washington D.C.

Klein, David R. 1979. Alaska oil pipeline in retrospect. Transactions of the North American Wildlife and Natural Resource Conference Vol. 44.

Klein, D. R. 1981. Alternate species for northern animal production. Canadian Journal of Animal Science, 61(1): 7-15.

Klein, David R. 1989. Subsistence. pp 51-53 in Hudson, Robert J. Wildlife production systems: economic utilisation of wild ungulates. Eds. K. R. Drew, and Leonid Mironovich Baskin. Cambridge University Press, UK.

Klein, David R. 2002. Perspectives on wilderness in the Arctic. Wilderness in the circumpolar north: searching for compatibility in ecological, traditional, and ecotourism values. USDA, Ogden UT.

Klein, D. R., & Magomedova, M. 2003. Industrial development and wildlife in arctic ecosystems. pp. 35-56 In Social and environmental impacts in the North: Methods in evaluation of socio-economic and environmental consequences of mining and energy production in the Arctic and Sub-Arctic. Springer. Netherlands.

Kofinas, G. P., F. S. Chapin III, S. Burnsilver, J. I. Schmidt, N. L. Fresco, K. Kielland, S. Martin, A. Springsteen, and T. S. Rupp. 2010. Resilience of Athabascan subsistence systems to interior Alaska’s changing climate. Canadian Journal of Forest Research 40:1347–1359.

Streever, W. 2002. Science and emotion, on ice: the role of science on Alaska's North Slope. Bioscience 52:179–184.

Streever, W., R. Suydam, J. F. Payne, R. Shuchman, B. Streever, R. Suydam, J. F. Payne, R. Shuchman, R. P. Angliss, G. Balogh, J. Brown, J. Grunblatt, S. Guyer, D. L. Kane, J. J. Kelley, G. Kofinas, D. R. Lassuy, W. Loya, P. Martin, S. E. Moore, W. S. Pegau, C. Rea, D. J. Reed, T. Sformo, M. Sturm, J. J. Taylor, T. Viavant, D. Williams, and D. Yokel. 2011. Environmental change and potential impacts: applied research priorities for Alaska's North Slope. Arctic 64:390–397.

*PLANTS*

Breen, A. L. 2014. Balsam poplar (Populus balsamifera L.) communities on the Arctic Slope of Alaska. Phytocoenologia 44:1–24. 

Bryant, J. P., Chapin III, F. S., & Klein, D. R. 1983. Carbon/nutrient balance of boreal plants in relation to vertebrate herbivory. Oikos 40(3): 357-368.

Kade A., Walker D. A. 2008. Experimental alteration of vegetation on nonsorted circles: effects on cryogenic activity and implications for climate change in the Arctic. Arctic, Antarctic, and Alpine Research 40: 96-103.

Klein, D. R., Bruun, H. H., Lundgren, R., & Philipp, M. 2008. Climate change influences on species interrelationships and distributions in high-Arctic Greenland. Advances in Ecological Research, 40: 81-100.

Schickhoff U, Walker MD, Walker DA. 2002. Riparian willow communities on the Arctic Slope of Alaska and their environmental relationships: A classification and ordination analysis. Phytocoenologia 32: 145-204.

Streever, W. J., J. D. McKendrick, L. Fanter, S. C. Anderson, J. G. Kidd, and K. M. Portier. 2003. Evaluation of percent cover requirements for revegetation of disturbed sites on Alaska's North Slope. Arctic 56:234–248.

Walker D. A., Everett K. R. 1991. Loess ecosystems of northern Alaska: regional gradient and toposequence at Prudhoe Bay. Ecological Monographs 61: 437-464.

Walker D. A., et al. 1998. Energy and trace-gas fluxes across a soil pH boundary in the Arctic. Nature 394: 469- 472.

Walker D. A., Bockheim JG, Chapin FS, III, Eugster W, Nelson FE, Ping CL. 2001. Calcium-rich tundra, wildlife, and ‘’the Mammoth Steppe’’. Quaternary Science Reviews 20: 149-163.

Walker D. A., Kuss HP, Epstein HE, Kade AN, Vonlanthen C, Raynolds MK, Daniëls FJA. 2011. Vegetation of zonal patterned-ground ecosystems along the North American Arctic Transect. Applied Vegetation Science 14: 435-606.

Walker, D. A., T. D. Hamilton, H. A. Maier, C. A. Munger, and M. K. Raynolds. 2014. Glacial history and long- term ecology in the Toolik Lake region. Pages 61–80 in J. E. Hobbie and G. W. Kling, editors. Alaska's changing Arctic: Ecological consequences for tundra, streams, and lakes. University of Alaska Press.

*SOILS AND PERMAFROST*

Daanen, R. P., G. Grosse, M. M. Darrow, T. D. Hamilton, and B. M. Jones. 2012. Rapid movement of frozen debris-lobes: implications for permafrost degradation and slope instability in the south-central Brooks Range, Alaska. Natural Hazards and Earth System Sciences 12:1521–1537.

French, H., and Y. Shur. 2010. The principles of cryostratigraphy. Earth Science Reviews 101:190–206.

Kanevskiy, M., H. French, Y. Shur, K. Bjella, M. Bray, C. Colllins, T. Douglas, and D. Fortier. 2008. Late- Pleistocene syngenetic permafrost in the CRREL permafrost tunnel, Fox, Alaska. University of Alaska, Institute of Northern Engineering, Fairbanks, Alaska.

Kanevskiy, M., Y. Shur, B. Connor, M. Dillon, E. Stephani, and J. O'Donnell. 2012. Study of ice-rich syngenetic permafrost for road design (interior Alaska). Proceedings Tenth International Permafrost Conference, Tyumen, Russia:191–196.

Kanevskiy, M., Shur, Y., Jorgenson, M.T., Ping, C.-L., Michaelson, G.J., Fortier, D., Stephani, E., Dillon, M., Tumskoy, V. 2013. Ground ice in the upper permafrost of the Beaufort Sea Coast of Alaska. Cold Regions Science and Technology 85, 56-70.

Ping CL, Michaelson GJ, Kimble JM, Romanovsky VE, Shur YL, Swanson DK, Walker DA. 2008. Cryogenesis and soil formation along a bioclimate gradient in Arctic North America. Journal of Geophysical Research - Biogeosciences 113: G03S12.

Ping CL, Michaelson GJ, Jorgenson MT, Kimble JM, Epstein H, Romanovsky VE, Walker DA. 2008. High stocks of soil organic carbon in North American Arctic region. Nature Geoscience 1: 615-619.

Shur, Y. L., and M. T. Jorgenson. 2007. Patterns of permafrost formation and degradation in relation to climate and ecosystems. Permafrost and Periglacial Processes 18:7–19.

