# Preface {.unnumbered}

Welcome to the Alaska Geography Field Course! We are glad you are here and are excited to get to know you and your goals as they relate to soil science and this course. This is not a traditional classroom-style course, so the we view ourselves as facilitators on your journey to learn about the geography of soils and permafrost in Alaska. This syllabus outlines course expectations and logistical details. For more information about technical content see the guidebook.

<p> </p>

<p> </p>

## Instructors

::: callout-note
## Teaching Team

Dr. Alexander (Sasha) Kholodov

alkholodov\@alaska.edu

Dr. Nic Jelinski

jeli0026\@umn.edu

Dr. Amy Breen

albreen\@alaska.edu
:::

## Course Format

The class will begin with some introductory soil science and ecology lectures, introduction to arctic soil processes, Alaska in general, and a discussion of what we are likely to encounter throughout the course. Fieldwork will begin gradually, gaining in complexity and intensity with movement north; especially north of Fairbanks. Throughout the course, we will be camping many nights with a few nights of "civilization" in Fairbanks that will let you rest a bit more comfortably, launder some clothes, and prepare for more time in the field. Once we leave Fairbanks, there will be very little in the way of provisions, so please come prepared with all needed gear. If you have ANY questions, kindly contact one of the instructors for guidance.
