# Course Logistics

## Registration

All participants must be registered for NRM 489/689 through the University of Alaska Fairbanks. Participation requires registration for the course, but participants do not need to be degree-seeking students.

## Tuition, Course Fees and Expenses

- Course tuition differs between NRM 489 (undergraduate) and NRM 689 (graduate). The estimated tuition for NRM 489 is $289 (AK residents), $855 (Non-residents), and $434 (WUE). The estimated tuition for NRM 689 is $539 (AK Residents) and $1,105 (Non-residents). You can choose which version of the course to register for based on your needs, regardless of your status at your home institution. If you need graduate credit on your UAF transcript, however, please register for NRM 689.

- A lab fee of $1410 per student for NRM 489 (NRM 689 fees are slightly higher). These fees go toward fleet vehicles, gas, food (all meals are included except three restaurant dinners in Fairbanks), lodging, entrance fees for activities (excluding optional tours), and field tools and materials. For a more detailed breakdown of course fee usage, please contact the instructors.

- Students are responsible for arranging their own lodging if they arrive early or plan to stay after the course dates.

- All food will be provided except for three dinners on your own. Please talk with one of the instructors if you feel you cannot afford these dinners.

- Most scheduled activities are included in the course fee, but there are several opportunities for optional activities that may include out-of-pocket expenses.

- Total expense estimates

| Course Number | Residency Status | Tuition  | Lab Fees  | Additional Meals | Airfare (estimated) | Cumulative Cost |
|---------|------------|----------|-----|---------|------------|
| NRM 489      | Resident       | $289   | $1410 | $75 | $500 | $2,274 |
| NRM 489      | Non-Resident       | $855   | $1410 | $75 | $500 | $2,840 |
| NRM 689      | Resident       | $539   | $1410 | $75 | $500 | $2,524 |
| NRM 689      | Non-Resident       | $1105   | $1410 | $75 | $500 | $3,090 |

## Travel

Students are responsible for arranging their own flights/transportation to
Anchorage (arriving on Friday, July 11th) and departure from Fairbanks (departing on Thursday, July 24th). Any lodging for extra nights at the beginning or end of the trip are the sole responsibility of the student. All other transportation during the course is provided.

- Arrival into Anchorage: Friday, July 11th. If possible, plan to arrive prior to 4pm - let us know if this is not possible. The instructors will provide shuttle service from the Anchorage Airport. Once you have booked your flight, please provide arrival information [here](xxxx). If you are local in Alaska please indicate that you will not need an airport shuttle.

- Departure from Fairbanks: Thursday, July 24th. You should plan to depart from Fairbanks no earlier than 8:00pm - please contact the instructors if this is not possible.  Shuttles to the airport will be provided. Once you have booked your flight, please provide departure information [here](xxxx). If you are local in Alaska please indicate that you will not need an airport shuttle in Fairbanks.

## Dietary Preferences, Medical Information, and Emergency Contacts

To allow us to plan for and accomodate dietary preferences as best as possible, understand any personal medical requirements you may have, and develop a list of emergency contacts, please complete [this Google Form](xxxx) no later than June 1st, 2025.

## Grading

This course is graded as pass/fail. We want everyone to pass! There are no formal exams or quizzes, so a passing grade will be based on the following:

- Attention during introductory instruction activities

- Participation during group learning activities in the classroom and field

- Thoughtfully completing surveys and reflections activities (3 or 4 total)

- Helping with group meal preparation and cleanup as well as any other essential group needs such as cleaning vehicles, hauling water and gear, shopping for food/supplies, and packing vehicles.

The instructors follow the University of Alaska Fairbanks Incomplete Grade Policy: The letter “I” (Incomplete) is a temporary grade used to indicate that the student has satisfactorily completed (C or better) the majority of work in a course but for personal reasons beyond the student’s control, such as sickness, has not been able to complete the course during the regular semester. Negligence or indifference are not acceptable reasons for an “I” grade.

## Course Dates At-A-Glance

An brief overview of the schedule is provided below. For a detailed schedule, please see the Course Schedule section of this syllabus.

| Day | Date | Activity  |
|----|----|----|
| 1 | 11JUL | Students arrive to Anchorage. Set Up a camp at the Experimental Farm in Palmer. |
| 2| 12JUL | Morning: Class introduction, lectures. Afternoon - either Musk Ox farm or hiking at the Independence Mine. |
| 3| 13JUL | Morning: Matanuska glacier. Afternoon: Soil pit at the station (students intro in the routine of group work around a soil pit). |
| 4| 14JUL | Morning: Wrap up a camp. Drive to the Fishhook site, soil pit (Andisol). Afternoon: Drive to DNP/Healy, set up camp.|
| 5| 15JUL | Denali Park. Hiking, visitor center, NPS rangers lecture (?).|
| 6| 16JUL | Morning: Wrap up camp. Two soil pits at the Eight Mile Lake site (Gelisol and Spodosol). Afternoon: Drive to Fairbanks.|
| 7| 17JUL | Morning: visit to the CRREL Permafrost Tunnel. Afternoon: Smith Lake transect, two soil pits (Inceptisol and Gelisol).|
| 8| 18JUL |Free day in Fairbanks. Grocery. Potentially - trip to Chena Hot Springs.|
| 9| 19JUL | Drive to Coldfoot/Marion Creek campground. Impact of wildfires on the ecosystem. Two soil pits, burned and unburned (Inceptisol and Gelisol). Set up camp.|
| 10| 20JUL | Brooks Range foothills. Three soil its: Gelisols (Histel at the bog and Turbel at palsas) and Entisol at river bank. IRIS tubes. Evening - hike to waterfalls (optional). |
| 11| 21JUL | Morning: Wrap up camp. Drive up north. Few observation stops (frozen debris lobe, northernmost tree, stone circles). One soil pit (Gelisol). Stop for gas in TFS.|
| 12| 22JUL | Arctic Coastal Plain. Soil pit at Franklin Bluffs (Turbel). Description of the river bluf (Gelisol). Evening - hike to pingo in Deadhorse.|
| 13| 23JUL | Drive down south. Stop for gas at the TFS. Soil pit/river bluff (Geloll). Evening: set up a camp. |
| 14| 24JUL | Morning: Wrap up camp. Drive to Fairbanks. One stop (bog). Students departure.|






