# What to Expect and Packing Lists

## What to Expect!

- The weather will vary dramatically. We will plan to work through the rain and cold, so dress accordingly.

- Wildlife. Bears are prevalent in many parts of Alaska. We will observe wildlife safety practices and also will be traveling in a group at all times so any unexpected encounters will be unlikely.

- North of Fairbanks, there will be no electricity and limited cell phone reception for several days.

- Mosquitos may be extremely thick at times. All students are strongly encouraged to
bring repellant and a bug net to wear over your head. More information in packing list.

- When we are camping, everyone will need to pitch in to help cook and clean. **We will do everything in our power to accomodate dietary preferences/needs**. Breakfast generally consists of quick oats, eggs, bacon, coffee, fruit, etc. Lunches are mostly cold cut sandwiches, chips, fruit, etc. Dinners will be something easy to prepare in camp; typically spaghetti, nachos, tuna casserole, hamburgers, etc. We eat well– do not worry.

## Packing List

Under construction.